cursor            #ffb4aa
cursor_text_color #561e18

foreground            #f1dedc
background            #140c0b
selection_foreground  #442926
selection_background  #e7bdb7
url_color             #e7bdb7
